v1 = input("Please Enter 1 st Value:")
v2 = input("Please Enter 2 nd Value:")
v3 = input("Please Enter 3 th Value:")
v4 = input("Please Enter 4 th Value:")
v5 = input("Please Enter 5 th Value:")
print('1 st Value {}'.format(v1))
print('2 nd Value {}'.format(v2))
print('1 th Value {}'.format(v3))
print('1 th Value {}'.format(v4))
print('1 th Value {}'.format(v5))
